[solution]
name = "gdn-decode-cuda-reduction"
definition = "gdn_decode_qk4_v8_d128_k_last"
author = "team-name"

[build]
language = "cuda"
entry_point = "gdn_decode_kernel_4.cu::gdn_decode_v4"
destination_passing_style = true

#language = "python"
#entry_point = "gdn_decode_cutedsl.py::gated_delta_rule_decode"
#destination_passing_style = false

#language = "tilelang"
#entry_point = "gdn_decode.py::run"
#destination_passing_style = false
