[solution]
name = "gdn-decode-cuda-naive"
definition = "gdn_decode_qk4_v8_d128_k_last"
author = "team-name"

[build]
language = "cuda"
entry_point = "gdn_decode_kernel_1.cu::gdn_decode"
destination_passing_style = true
