[solution]
name = "gdn-prefill-triton"
definition = "gdn_prefill_qk4_v8_d128_k_last"
author = "CUDA_ERROR_UNKNOWN"

[build]
language = "python"
entry_point = "chunk_v6b_o_v1b.py::run"
destination_passing_style = false

#language = "python"
#entry_point = "main.py::run"
#destination_passing_style = false
