[solution]
name = "gdn-prefill-final"
definition = "gdn_prefill_qk4_v8_d128_k_last"
author = "CUDA_ERROR_UNKNOWN"

[build]
language = "python"
entry_point = "gdn_prefill_mix.py::run"
destination_passing_style = false
